### ISSUE TITLE
powerdns::recursor is installing pdns-server

### ISSUE THREAD

**Issue by jamesmollison** [christiangda/puppet-powerdns#6]
With the latest release of this module on ubuntu (xenial), the powerdns::recursor class is installing the 'pdns-server' server package and trying to start the service - and failing to do so - as both pdns-server and pdns-recursor can't run concurrently.

This behaviour didn't exist previously. We're only using the recursor class, so we have no need use the main server class - and we haven't configured any part of that functionality.  Perhaps the recursor should be a seperate class? 

Our config is exactly as specified in the readme - Let me know if you need any specific information about this setup

**Comment by jamesmollison** [comment]
Assuming this is to do with changes to line 61-63 in init.pp with latest release

**Comment by christiangda** [comment]
Hi @jamesmollison , thanks for report this issue, you are right, but the problem is not here , is in inheritance for recursor class, doing more specific:

 Line 14 of recursor class,

before:

```
  ) inherits powerdns {
```

after:

```
  ) inherits powerdns::params {
```

I'm doing acceptance test to prevent this kind of problems. let me just one moment and I fixing  that.
My apologies for this issue.
